# Based on https://gitlab.cern.ch/gitlabci-examples/build_docker_image/-/blob/master/.gitlab-ci.yml
stages:
  - build
  - test
  - deploy

docker-build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - |
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        export IMAGE_DESTINATION=gitlab-registry.cern.ch/syclops/adaptiveperfhtml:latest
      else
        export IMAGE_DESTINATION=gitlab-registry.cern.ch/syclops/adaptiveperfhtml:$CI_COMMIT_BRANCH
      fi
    # Prepare Kaniko configuration file
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # Build and push the image from the Dockerfile at the root of the project.
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION
    # Print the full registry path of the pushed image
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"

docker-test:
  image:
    name: gitlab-registry.cern.ch/syclops/adaptiveperfhtml:$CI_COMMIT_BRANCH
    entrypoint: [""]
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - pytest

syclops-pviewer-deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Deployment goes here"