# Based on https://gitlab.cern.ch/gitlabci-examples/build_docker_image/-/blob/master/.gitlab-ci.yml
stages:
  - build
  - test
  - deploy

docker-build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - |
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        export IMAGE_DESTINATION=gitlab-registry.cern.ch/adaptiveperf/adaptiveperfhtml:latest
      else
        export IMAGE_DESTINATION=gitlab-registry.cern.ch/adaptiveperf/adaptiveperfhtml:$CI_COMMIT_BRANCH
      fi
    # Prepare Kaniko configuration file
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # Build and push the image from the Dockerfile at the root of the project.
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION
    # Print the full registry path of the pushed image
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"

docker-test:
  image:
    name: gitlab-registry.cern.ch/adaptiveperf/adaptiveperfhtml:$CI_COMMIT_BRANCH
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - pytest

docker-test-main:
  image:
    name: gitlab-registry.cern.ch/adaptiveperf/adaptiveperfhtml:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - pytest

syclops-pviewer-deploy:
  # Based on https://paas.docs.cern.ch/2._Deploy_Applications/Deploy_Docker_Image/2-automatic-redeployments/#integrate-redeployment-in-ci-workflow
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  variables:
    SERVER: https://api.paas.okd.cern.ch
    PROJECT: syclops-pviewer
    APP_NAME: profilingviewer
  script:
    - oc login $SERVER --token=$DEPLOY_TOKEN
    - oc project $PROJECT
    - oc import-image $APP_NAME --all
    - sleep 10 && oc rollout status deployment/$APP_NAME
