# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: LGPL-3.0-or-later

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG != null
    - if: $CI_COMMIT_BRANCH == "dev"

# Most of the content below is based on https://gitlab.cern.ch/gitlabci-examples/build_docker_image/-/blob/master/.gitlab-ci.yml
stages:
  - licensing-check
  - build
  - docs
  - docs-deploy

reuse-lint:
  image:
    name: registry.cern.ch/docker.io/fsfe/reuse
    entrypoint: [""]
  stage: licensing-check
  script:
    - reuse lint

# docker-build:
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   stage: build
#   script:
#     # Prepare Kaniko configuration file
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#     # Build and push the image from the Dockerfile at the root of the project.
#     - |
#       if [[ "$CI_COMMIT_TAG" != "" ]]; then
#         IMAGE_DESTINATION=gitlab-registry.cern.ch/adaptyst/adaptyst-analyser:latest
#         IMAGE_DESTINATION_NAMED=gitlab-registry.cern.ch/adaptyst/adaptyst-analyser:$CI_COMMIT_TAG
#         /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION --destination $IMAGE_DESTINATION_NAMED
#       else
#         IMAGE_DESTINATION=gitlab-registry.cern.ch/adaptyst/adaptyst-analyser:branch-$CI_COMMIT_BRANCH
#         /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION
#       fi
#     # Print the full registry path of the pushed image
#     - echo "Image pushed successfully to ${IMAGE_DESTINATION}"

js-docs-gen:
  image:
    name: registry.cern.ch/docker.io/ubuntu:latest
  stage: docs
  before_script:
    - apt-get update
    - apt-get install -y npm
    - npm install -g jsdoc
  script:
    - cd docs/javascript
    - jsdoc -c config.json home.md ../../src/adaptystanalyser/static/viewer.js
  artifacts:
    paths:
      - docs/javascript/out
    expire_in: 6 h

python-docs-gen:
  image:
    name: registry.cern.ch/docker.io/python:latest
  stage: docs
  before_script:
    - pip install -U sphinx
  script:
    - sphinx-build -b html docs/python docs/python/_build
  artifacts:
    paths:
      - docs/python/_build
    expire_in: 6 h

js-docs-deploy:
  image:
    name: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  stage: docs-deploy
  rules:
    - if: $CI_COMMIT_TAG != null
  script:
    - export EOS_PATH=$EOS_PATH_JS_DOCS
    - mv docs/javascript/out public
    - deploy-eos

python-docs-deploy:
  image:
    name: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  stage: docs-deploy
  rules:
    - if: $CI_COMMIT_TAG != null
  script:
    - export EOS_PATH=$EOS_PATH_PYTHON_DOCS
    - mv docs/python/_build public
    - deploy-eos
